version: '3.9'
networks:
{% if 'alesharik.baseinfra.nginx_proxy' in ansible_role_names %}
  proxy:
    external:
      name: nginx-proxy_proxy
{% endif %}
services:
  nginx:
{% if nginx.static.git.pull_token is defined %}
    build: .
{% else %}
    image: "{{ nginx.static.git.image }}"
{% endif %}
    restart: always
    user: "{{ userinfo.uid }}"
    environment:
      VIRTUAL_HOST: "{{ nginx.static.git.host }}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "{{ nginx.static.git.host }}"
    volumes:
      - "{{ dir.data }}/nginx-static-{{ nginx.static.git.name }}:/var/www"
      - "{{ dir.ansible }}/nginx-static-git-{{ nginx.static.git.name }}/nginx.conf:/etc/nginx/nginx.conf"
      - "/home/{{ nginx.static.git.name }}/.ssh/id_ecdsa:/id_ecdsa"
{% if 'alesharik.baseinfra.nginx_proxy' in ansible_role_names %}
    networks:
      - proxy
{% endif %}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/.health" ]
      interval: 30s
      timeout: 20s
      retries: 3