---
- name: Create compose dir
  ansible.builtin.file:
    path: "{{ dir.ansible }}/vmagent"
    state: directory
    mode: 0755
  tags: vmagent
- name: Create data dir
  ansible.builtin.file:
    path: "{{ dir.data }}/vmagent"
    state: directory
    owner: '10001'
    mode: 0700
  tags: vmagent

- name: Read password
  tags: vmagent
  shell: |
    cat {{ dir.ansible }}/vmagent/password
  register: pwd
  ignore_errors: true

- name: Set password fact
  tags: vmagent
  set_fact:
    pwd: "{{ pwd.stdout }}"
  when: pwd is defined

- name: Generate password
  tags: vmagent
  set_fact:
    pwd: "{{ lookup('ansible.builtin.password', '/dev/null', length=24, chars=['ascii_letters', 'digits']) }}"
  when: pwd is not defined

- name: Write password
  copy:
    dest: "{{ dir.ansible }}/vmagent/config/password"
    content: "{{ pwd }}"
    group: root
    owner: root
    mode: 0550
  tags: vmagent
  notify:
    - restart vmagent

- name: Move compose files
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ dir.ansible }}/vmagent/docker-compose.yml"
    mode: 0755
  tags: vmagent
  notify:
    - restart vmagent
- name: Make config folder
  ansible.builtin.file:
    path: "{{ dir.ansible }}/vmagent/config"
    state: directory
    mode: 0755
  tags: vmagent
- name: Make extended config folder
  ansible.builtin.file:
    path: "{{ dir.ansible }}/vmagent/config/conf.d"
    state: directory
    mode: 0755
  tags: vmagent
- name: Move config
  ansible.builtin.template:
    src: config.yaml
    dest: "{{ dir.ansible }}/vmagent/config/config.yml"
    mode: 0755
  tags: vmagent
  notify:
    - restart vmagent

- name: Clear password
  set_fact:
    pwd: ''
  tags: vmagent

- name: Create private key
  tags: vmagent
  community.crypto.openssl_privatekey:
    path: "{{ dir.ansible }}/vmagent/config/client.key"
    group: root
    owner: root
    mode: 0550
  notify:
    - restart vmagent
- name: Create certificate signing request (CSR) for new certificate
  tags: vmagent
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ dir.ansible }}/vmagent/config/client.key"
  register: csr
- name: Sign certificate with our CA
  tags: vmagent
  become: no
  vars:
    ansible_remote_tmp: "{{ playbook_dir }}/tmp"
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ csr.csr }}"
    provider: ownca
    ownca_path: "{{ playbook_dir }}/certs/mimir_ca.pem"
    ownca_privatekey_path: "{{ playbook_dir }}/certs/mimir_ca.key"
    ownca_not_after: +365d  # valid for one year
    ownca_not_before: "-1d"  # valid since yesterday
  delegate_to: 127.0.0.1
  register: cert
- name: Write certificate
  copy:
    dest: "{{ dir.ansible }}/vmagent/config/client.cer"
    content: "{{ cert.certificate }}"
    group: root
    owner: root
    mode: 0550
  tags: vmagent
  notify:
    - restart vmagent
- name: Write CA
  copy:
    src: "{{ playbook_dir }}/certs/mimir_ca.pem"
    dest: "{{ dir.ansible }}/vmagent/config/ca.pem"
    owner: root
    group: root
    mode: 0550
  tags: vmagent
  notify:
    - restart vmagent

- name: Start vmagent
  community.docker.docker_compose_v2:
    project_src: "{{ dir.ansible }}/vmagent"
    state: present
  tags: vmagent

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers
  tags: vmagent
