---
- name: Create compose dir
  ansible.builtin.file:
    path: "{{ vmagent.directories.ansible }}"
    state: directory
    mode: "0755"
  tags: vmagent
- name: Create data dir
  ansible.builtin.file:
    path: "{{ vmagent.directories.data }}"
    state: directory
    owner: '10001'
    mode: "0700"
  tags: vmagent
- name: Make config folder
  ansible.builtin.file:
    path: "{{ vmagent.directories.ansible }}/config"
    state: directory
    mode: "0755"
  tags: vmagent
- name: Make extended config folder
  ansible.builtin.file:
    path: "{{ vmagent.directories.ansible }}/config/conf.d"
    state: directory
    mode: "0755"
  tags: vmagent

- name: Read password
  tags: vmagent
  ansible.builtin.shell: |
    cat {{ vmagent.directories.ansible }}/config/password
  register: vmagent_password_raw
  changed_when: false
  ignore_errors: true

- name: Set password fact
  tags: vmagent
  ansible.builtin.set_fact:
    vmagent_password: "{{ vmagent_password_raw.stdout }}"
  when: vmagent_password_raw is defined

- name: Generate password
  tags: vmagent
  ansible.builtin.set_fact:
    vmagent_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=24, chars=['ascii_letters', 'digits']) }}"
  when: not vmagent_password | default(None)

- name: Write password
  ansible.builtin.copy:
    dest: "{{ vmagent.directories.ansible }}/config/password"
    content: "{{ vmagent_password }}"
    group: root
    owner: root
    mode: "0550"
  tags: vmagent
  notify:
    - restart vmagent

- name: Move compose files
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ vmagent.directories.ansible }}/docker-compose.yml"
    mode: "0755"
  tags: vmagent
  notify:
    - restart vmagent
- name: Move config
  ansible.builtin.template:
    src: config.yaml
    dest: "{{ vmagent.directories.ansible }}/config/config.yml"
    mode: "0755"
  tags: vmagent
  notify:
    - restart vmagent

- name: Clear password
  ansible.builtin.set_fact:
    vmagent_password: ''
  tags: vmagent

- name: Start vmagent
  community.docker.docker_compose_v2:
    project_src: "{{ vmagent.directories.ansible }}"
    state: present
  tags: vmagent

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers
  tags: vmagent
