networks:
  clickhouse:
    name: clickhouse
services:
  clickhouse:
    image: "{{ clickhouse.image }}:{{ clickhouse.version }}"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    user: '1002'
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_ROOT_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_ROOT_PASSWORD}
      CLICKHOUSE_INIT_TIMEOUT: 300
    volumes:
      - ./init-defaults.sh:/docker-entrypoint-initdb.d/init-defaults.sh:ro
      - "{{ dir.data }}/clickhouse:/var/lib/clickhouse:cached"
    networks:
      - clickhouse
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      prometheus.io.path: /metrics
      prometheus.io.port: 9363 # port
      prometheus.io.instance: "{{ inventory_hostname }}"