version: '3.9'
networks:
  clickhouse:
services:
  clickhouse:
    image: "clickhouse/clickhouse-server:{{ clickhouse.version }}"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_ROOT_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_ROOT_PASSWORD}
      CLICKHOUSE_INIT_TIMEOUT: 60
    volumes:
      - ./init-defaults.sh:/docker-entrypoint-initdb.d/init-defaults.sh:ro
{% if clickhouse.volume_override is defined %}
      - "ext:/var/lib/clickhouse:cached"
{% else %}
      - "{{ clickhousegen_directory }}:/var/lib/clickhouse:cached"
{% endif %}
    networks:
      - clickhouse
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
{% if clickhouse.volume_override is defined %}
volumes:
  ext:
    name: "{{ clickhouse.volume_override }}"
    external: true
{% endif %}