---
- name: Create compose dir
  ansible.builtin.file:
    path: "{{ dir.ansible }}/clickhouse"
    state: directory
    mode: 0700
  tags: clickhouse
- name: Move compose files
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ dir.ansible }}/clickhouse/docker-compose.yml"
    mode: 0700
  tags: clickhouse
  notify:
    - restart clickhouse
- name: Move env file
  ansible.builtin.template:
    src: .env
    dest: "{{ dir.ansible }}/clickhouse/.env"
    mode: 0700
  tags: clickhouse
  notify:
    - restart clickhouse
- name: Move init-defauts.sh file
  ansible.builtin.template:
    src: init-defaults.sh
    dest: "{{ dir.ansible }}/clickhouse/init-defaults.sh"
    mode: 0700
    owner: 1002
  tags: clickhouse
  notify:
    - restart clickhouse

- name: Create clickhouse directory
  ansible.builtin.file:
    path: "{{ dir.data }}/clickhouse"
    state: directory
    owner: 1002
    mode: 0700
  tags: clickhouse

- name: Start clickhouse
  community.docker.docker_compose_v2:
    project_src: "{{ dir.ansible }}/clickhouse"
    state: restarted
  tags: clickhouse

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers
  tags: clickhouse
