---
- name: Create compose dir
  ansible.builtin.file:
    path: "{{ dir.ansible }}/grafana"
    state: directory
    mode: 0755
  tags: grafana
- name: Create data dir
  ansible.builtin.file:
    path: "{{ dir.data }}/grafana"
    state: directory
    mode: 0755
    owner: '472'
  tags: grafana

- name: Move compose files
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ dir.ansible }}/grafana/docker-compose.yml"
    mode: 0755
  tags: grafana
  notify:
    - restart grafana
- name: Move admin password
  ansible.builtin.template:
    src: admin_password.txt
    dest: "{{ dir.ansible }}/grafana/admin_password.txt"
    mode: 0755
  tags: grafana
  notify:
    - restart grafana

- name: Start grafana
  tags: grafana
  community.docker.docker_compose_v2:
    project_src: "{{ dir.ansible }}/grafana"
    state: present

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers
  tags: grafana
