---
- name: Create CA private key
  community.crypto.openssl_privatekey:
    path: "{{ playbook_dir }}/certs/mimir_ca.key"
  delegate_to: 127.0.0.1
  become: no
  tags: mimir
  vars:
    ansible_remote_tmp: "{{ playbook_dir }}/tmp"
- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ playbook_dir }}/certs/mimir_ca.key"
    common_name: Mimir CA
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  delegate_to: 127.0.0.1
  tags: mimir
  become: no
  register: ca_csr
  vars:
    ansible_remote_tmp: "{{ playbook_dir }}/tmp"
- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ playbook_dir }}/certs/mimir_ca.pem"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ playbook_dir }}/certs/mimir_ca.key"
    provider: selfsigned
  delegate_to: 127.0.0.1
  tags: mimir
  become: no
  vars:
    ansible_remote_tmp: "{{ playbook_dir }}/tmp"