---
- name: Create compose dir
  ansible.builtin.file:
    path: "{{ dir.ansible }}/nginx-proxy"
    state: directory
    mode: 0755
  tags: nginx_proxy_base

- name: Create vhosts directory
  ansible.builtin.file:
    path: "{{ dir.ansible }}/nginx-proxy/vhost.d"
    state: directory
    mode: 0755
  tags: nginx_proxy_base

- name: Create nginx network
  community.docker.docker_network:
    name: nginx-proxy