services:
  watchtower:
    container_name: watchtower
    image: "{{ watchtower.image }}:{{ watchtower.version }}"
    restart: always
    environment:
      WATCHTOWER_ROLLING_RESTART: 'true'
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "{{ inventory_hostname }}"
{% if watchtower.notification_url is defined %}
      WATCHTOWER_NOTIFICATION_URL: '{{ watchtower.notification_url }}'
{% endif %}
{% if watchtower_http_token is defined %}
      WATCHTOWER_LABEL_ENABLE: 'true'
      WATCHTOWER_HTTP_API_METRICS: 'true'
      WATCHTOWER_HTTP_API_TOKEN: "{{ watchtower_http_token }}"
{% endif %}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: "--interval {{ wattower.interval }}"