- job_name: "docker-watchtower"
  scrape_interval: 5s
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
  relabel_configs:
    - source_labels: [__meta_docker_container_name]
      regex: watchtower
      action: keep
    - regex: __meta_docker_container_name
      action: labelmap
      replacement: container_name
  bearer_token: "{{ watchtower_http_token }}"