---
- name: Get current hostname
  ansible.builtin.command: hostname
  changed_when: false
  register: current_hostname

- name: Check hostname matches inventory name
  ansible.builtin.assert:
    that:
      - current_hostname.stdout == inventory_hostname

- name: Read /etc/hosts
  ansible.builtin.slurp:
    src: /etc/hosts
  register: etc_hosts

- name: Check /etc/hosts contains localhost alias
  ansible.builtin.assert:
    that:
      - "('127.0.0.1 localhost ' + inventory_hostname) in (etc_hosts.content | b64decode)"
