{% set hosts = [] %}
{% for h in minio.hosts %}
  {{ hosts.append(h.name) }}
{% endfor %}
networks:
  minio:
    name: minio
  proxy:
    name: nginx-proxy
    external: true
services:
  minio:
    image: "{{ minio.image }}:{{ minio.version }}"
    command: server --console-address ":9001" /data1
    restart: always
    environment:
      VIRTUAL_HOST: "{{ ','.join(hosts) }}"
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: "{{ ','.join(hosts) }}"
      MINIO_ROOT_USER: ${ROOT_USER}
      MINIO_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - "{{ dir.data }}/minio:/data1"
    networks:
      - minio
      - proxy
    labels:
      prometheus.io.path: /minio/v2/metrics/cluster
      prometheus.io.port: 9000
      prometheus.io.network: minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3