version: '3.9'
networks:
{% if 'alesharik.baseinfra.nginx_proxy' in ansible_role_names %}
  proxy:
    external:
      name: nginx-proxy_proxy
{% endif %}
services:
  nexus:
    image: "sonatype/nexus3:{{ nexus.version }}"
    restart: always
    environment:
      VIRTUAL_HOST: "{{ nexus.host }}"
      VIRTUAL_PORT: 8081
      LETSENCRYPT_HOST: "{{ nexus.host }}"
    volumes:
{% if nexus.volume_override is defined %}
      - "ext:/nexus-data"
{% else %}
      - "{{ nexus.directory }}:/nexus-data"
{% endif %}
{% if 'alesharik.baseinfra.nginx_proxy' in ansible_role_names %}
    networks:
      - proxy
{% endif %}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status" ]
      interval: 30s
      timeout: 20s
      retries: 3
{% if nexus.volume_override is defined %}
volumes:
  ext:
    name: "{{ nexus.volume_override }}"
    external: true
{% endif %}