---
loki:
  image: grafana/loki
  version: 2.7.4
  tls_hostname: loki.infra.local
  clients:
    - grafana
  retention:
    retention_period: 30d
    retention_stream:
      - selector: '{container_name="nginx-proxy"}'
        priority: 1
        period: 24h