---
loki:
  image: grafana/loki
  version: 3.5
  tls_hostname: loki.infra.local
  clients:
    - grafana
  allow_structured_metadata: true
  log_format: json
  retention:
    retention_period: 30d
    retention_stream:
      - selector: '{container_name="nginx-proxy"}'
        priority: 1
        period: 24h
  migrate_from_v11: false
  migration_dates:
    v11: "2020-10-24"
    v13: "2024-07-06"