---
loki:
  image: grafana/loki
  version: 3.1.0
  tls_hostname: loki.infra.local
  clients:
    - grafana
  retention:
    retention_period: 30d
    retention_stream:
      - selector: '{container_name="nginx-proxy"}'
        priority: 1
        period: 24h
  migration_dates:
    v11: "2020-10-24"
    v13: "2024-07-08"