version: '3.9'
networks:
  redis:
services:
  redis:
    image: "redis:{{ redis.version }}"
    command: redis-server --save 60 1 --requirepass ${REDIS_PASSWORD}
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDISCLI_AUTH: ${REDIS_PASSWORD}
    volumes:
      - "{{ redisgen_directory }}:/data"
    networks:
      - redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 20s
      retries: 3