networks:
  redis-{{ redis.name }}:
    name: 'redis-{{ redis.name }}'
services:
  redis:
    image: "{{ redis.image }}:{{ redis.version }}"
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDISCLI_AUTH: ${REDIS_PASSWORD}
      REDIS_DAEMON_USER: 1001
      REDIS_DAEMON_GROUP: 1001
    volumes:
      - "{{ dir.data }}/redis-{{ redis.name }}:/bitnami/redis/data"
    networks:
      - redis-{{ redis.name }}
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 20s
      retries: 3
{% if redis.exporter.enabled %}
  exporter:
    image: "{{ redis.exporter.image }}:{{ redis.exporter.version }}"
    restart: always
    environment:
      REDIS_ADDR: redis://redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - redis-{{ redis.name }}
    labels:
      prometheus.io.path: /
      prometheus.io.port: 9121 # port
      prometheus.io.instance: "{{ inventory_hostname }}-{{ redis.name }}"
{% endif %}