---
# 0700: this directory holds the CA private key
- name: Create local certs dir
  ansible.builtin.file:
    path: "{{ vault.directories.ca }}"
    state: directory
    mode: "0700"
  delegate_to: 127.0.0.1
  become: false
  run_once: true
  tags: vault

- name: Create CA private key
  community.crypto.openssl_privatekey:
    path: "{{ vault.directories.ca }}/ca.key"
    mode: "0600"
  delegate_to: 127.0.0.1
  become: false
  tags: vault
  run_once: true
  vars:
    ansible_remote_tmp: "{{ playbook_dir }}/tmp"

- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ vault.directories.ca }}/ca.key"
    organization_name: "{{ vault.pki.organization }}"
    organizational_unit_name: "{{ vault.pki.organizational_unit }}"
    common_name: Vault CA
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  delegate_to: 127.0.0.1
  tags: vault
  run_once: true
  become: false
  register: vault_ca_csr
  changed_when: false
  vars:
    ansible_remote_tmp: "{{ playbook_dir }}/tmp"

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ vault.directories.ca }}/ca.pem"
    csr_content: "{{ vault_ca_csr.csr }}"
    privatekey_path: "{{ vault.directories.ca }}/ca.key"
    provider: selfsigned
    mode: "0644"
  delegate_to: 127.0.0.1
  tags: vault
  become: false
  run_once: true
  vars:
    ansible_remote_tmp: "{{ playbook_dir }}/tmp"

- name: Write CA
  ansible.builtin.copy:
    src: "{{ vault.directories.ca }}/ca.pem"
    dest: "{{ vault.directories.tls }}/ca.pem"
    owner: vault
    group: vault
    mode: "0444"
  tags: vault
  notify:
    - restart vault
