- name: Install chrony
  tags: chrony
  ansible.builtin.apt:
    name: chrony
    state: present
- name: Setup config
  tags: chrony
  ansible.builtin.template:
    src: chrony.conf
    dest: /etc/chrony.conf
    mode: 0500
    owner: root
    group: root
- name: Stop systemd-timesyncd
  tags: chrony
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: false
  register: stop_service
  failed_when:
    - stop_service.failed == true
    - '"Could not find the requested service" not in stop_service.msg'
- name: Start chrony
  tags: chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    enabled: true
