auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 0
  log_format: {{ loki.log_format }}
  http_tls_config:
    cert_file: "/etc/loki/server.cer"
    key_file: "/etc/loki/server.key"
    client_auth_type: "RequireAndVerifyClientCert"
    client_ca_file: "/etc/loki/ca.pem"

common:
  path_prefix: /var/lib/loki
  replication_factor: 1
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
    object_store:
      filesystem:
        dir: /var/lib/loki/chunks
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

compactor:
  working_directory: /var/lib/loki/compaction
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

limits_config:
  allow_structured_metadata: {{ loki.allow_structured_metadata | lower }}
  {{ loki.retention | to_nice_yaml | indent(2) }}

storage_config:
  use_thanos_objstore: true
  tsdb_shipper:
    active_index_directory: /var/lib/loki/tsdb-index
    cache_location: /var/lib/loki/tsdb-cache

table_manager:
  retention_deletes_enabled: true
  retention_period: {{ loki.retention.retention_period }}

  storage:
schema_config:
  configs:
{% if loki.migrate_from_v11 %}
    - from: '{{ loki.migration_dates.v11 }}'
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
{% endif %}
    - from: '{{ loki.migration_dates.v13 }}'
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        period: 24h
        prefix: index_

#ruler:
#  alertmanager_url: http://localhost:9093

ruler_storage:
  filesystem:
    dir: /var/lib/loki/rules

analytics:
  reporting_enabled: false

ingester:
  chunk_encoding: snappy