auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 0
  http_tls_config:
    cert_file: "/etc/loki/server.cer"
    key_file: "/etc/loki/server.key"
    client_auth_type: "RequireAndVerifyClientCert"
    client_ca_file: "/etc/loki/ca.pem"

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

compactor:
  working_directory: /var/lib/loki/compaction
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  {{ loki.retention | to_nice_yaml | indent(2) }}

storage_config:
  tsdb_shipper:
    active_index_directory: /var/lib/loki/tsdb-index
    cache_location: /var/lib/loki/tsdb-cache

table_manager:
  retention_deletes_enabled: true
  retention_period: {{ loki.retention.retention_period }}

schema_config:
  configs:
    - from: '{{ loki.migration_dates.v11 }}'
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
    - from: '{{ loki.migration_dates.v13 }}'
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        period: 24h
        prefix: index_

#ruler:
#  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false

ingester:
  chunk_encoding: snappy