auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 0
  http_tls_config:
    cert_file: "/etc/loki/server.cer"
    key_file: "/etc/loki/server.key"
    client_auth_type: "RequireAndVerifyClientCert"
    client_ca_file: "/etc/loki/ca.pem"

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

compactor:
  working_directory: /var/lib/loki/compaction
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  retention_period: 30d
  retention_stream:
  - selector: '{container_name="nginx-proxy"}'
    priority: 1
    period: 24h

chunk_store_config:
  max_look_back_period: 30d

table_manager:
  retention_deletes_enabled: true
  retention_period: 30d

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

#ruler:
#  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false

ingester:
  chunk_encoding: snappy