version: '3.9'
services:
  loki:
    image: "{{ loki.image }}:{{ loki.version }}"
    restart: always
    command: -config.file=/etc/loki/config.yaml
    ports:
{% for h in (loki.listen_hosts | default([loki.host])) %}
      - "{{ h }}:3100:3100"
{% endfor %}
    volumes:
      - "{{ dir.data }}/loki:/var/lib/loki"
      - "{{ dir.ansible }}/loki/config:/etc/loki"