---
- name: Create compose dir
  ansible.builtin.file:
    path: "{{ dir.ansible }}/minio"
    state: directory
    mode: 0755
  tags: minio
- name: Move compose files
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ dir.ansible }}/minio/docker-compose.yml"
    mode: 0755
  tags: minio
  notify:
    - restart minio
- name: Move env file
  ansible.builtin.template:
    src: .env
    dest: "{{ dir.ansible }}/minio/.env"
    mode: 0755
  tags: minio
  notify:
    - restart minio
- name: Create minio directory
  ansible.builtin.file:
    path: "{{ minio.directory }}"
    state: directory
    mode: 0755
  when: minio.volume_override is not defined
  tags: minio

- name: Configure vhost
  tags: minio
  when: "'alesharik.baseinfra.nginx_proxy_base' in ansible_role_names"
  ansible.builtin.copy:
    dest: "{{ dir.ansible }}/nginx-proxy/vhost.d/{{ minio.host }}"
    content: |
              location /{{ minio.bucket }} {
                proxy_set_header Host $http_host;
                proxy_pass http://minio:9000/{{ minio.bucket }}/;
              }
    mode: 0755
  notify:
    - restart nginx-proxy

- name: Configure vhost location
  tags: minio
  when: "'alesharik.baseinfra.nginx_proxy_base' in ansible_role_names"
  ansible.builtin.copy:
    dest: "{{ dir.ansible }}/nginx-proxy/vhost.d/{{ minio.host }}_location"
    content: "return 404;"
    mode: 0755
  notify:
    - restart nginx-proxy

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers
  tags: minio
