- name: Configure vhost
  tags: minio
  ansible.builtin.copy:
    dest: "{{ dir.ansible }}/nginx-proxy/vhost.d/{{ domain.name }}"
    content: |
              location /{{ item }} {
                proxy_set_header Host $http_host;
                proxy_pass http://minio:9000/{{ item }}/;
              }
    mode: 0755
  notify:
    - restart nginx-proxy
  loop: "{{ domain.buckets }}"

- name: Configure vhost location
  tags: minio
  ansible.builtin.copy:
    dest: "{{ dir.ansible }}/nginx-proxy/vhost.d/{{ domain.name }}_location"
    content: "return 404;"
    mode: 0755
  notify:
    - restart nginx-proxy