server:
  http_listen_port: 9080
  grpc_listen_port: 0
  disable: true

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: "https://{{ loki.host }}:3100/loki/api/v1/push"
    batchsize: 100000
    external_labels:
      hostname: "{{ inventory_hostname }}"
    tls_config:
      ca_file: "/etc/promtail/ca.pem"
      cert_file: "/etc/promtail/client.cer"
      key_file: "/etc/promtail/client.key"
      server_name: "{{ loki.tls_hostname }}"


scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
{% for result in promtail.relabel_configs.systemd %}
      - {{ result | to_nice_yaml | indent(8) }}
{% endfor %}
{% if promtail.pipeline.common|length > 0 or promtail.pipeline.systemd|length > 0 %}
    pipeline_stages:
{% for result in promtail.pipeline.systemd %}
      - {{ result | to_nice_yaml | indent(8) }}
{% endfor %}
{% for result in promtail.pipeline.common %}
      - {{ result | to_nice_yaml | indent(8) }}
{% endfor %}
{% endif %}
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
{% for result in promtail.relabel_configs.docker %}
      - {{ result | to_nice_yaml | indent(8) }}
{% endfor %}

{% if promtail.pipeline.common|length > 0 or promtail.pipeline.docker|length > 0 %}
    pipeline_stages:
{% for result in promtail.pipeline.docker %}
      - {{ result | to_nice_yaml | indent(8) }}
{% endfor %}
{% for result in promtail.pipeline.common %}
      - {{ result | to_nice_yaml | indent(8) }}
{% endfor %}
{% endif %}