---
- name: Create compose dir
  ansible.builtin.file:
    path: "{{ wg_exporter.directories.ansible }}"
    state: directory
    mode: "0755"
  tags: wg_exporter

- name: Move compose files
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ wg_exporter.directories.ansible }}/docker-compose.yml"
    mode: "0755"
  tags: wg_exporter
  notify:
    - restart wg exporter

- name: Start wg exporter
  community.docker.docker_compose_v2:
    project_src: "{{ wg_exporter.directories.ansible }}"
    state: present
  tags: wg_exporter

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers
  tags: wg_exporter
