---
etcd: # noqa: var-naming[no-role-prefix]
  version: v3.6.12
  image: "quay.io/coreos/etcd"
  listen_ips: []
  networks: []
  env: []
  quorum: []
  vmagent: true
  directories:
    ansible: "{{ dir.ansible }}/etcd"
    data: "{{ dir.data }}/etcd"
    ca: "{{ playbook_dir }}/certs/etcd"
    vmagent_conf: "{{ vmagent.directories.ansible | default(dir.ansible ~ '/vmagent') }}/config/conf.d"
  pki:
    organization: "ETCD"
    organizational_unit: "Etcd"
