---
- name: Install docker on Ubuntu
  ansible.builtin.include_tasks: ubuntu.yaml
  when: ansible_facts['distribution'] == 'Ubuntu'
  tags: docker
- name: Install docker on Debian
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_facts['distribution'] == 'Debian'
  tags: docker
- name: Login into registries
  community.docker.docker_login:
    registry_url: "{{ item.key }}"
    username: "{{ item.value.username }}"
    password: "{{ item.value.password }}"
  loop: "{{ docker.registries | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  tags: docker
