---
- name: Create compose dir
  ansible.builtin.file:
    path: "{{ dir.ansible }}/headscale"
    state: directory
    mode: "0755"
  tags: headscale

- name: Create config dir
  ansible.builtin.file:
    path: "{{ dir.ansible }}/headscale/config"
    state: directory
    mode: "0755"
  tags: headscale

- name: Create data dir
  ansible.builtin.file:
    path: "{{ dir.data }}/headscale"
    state: directory
    mode: "0700"
    owner: 0
  tags: headscale

- name: Move config
  ansible.builtin.template:
    src: config.yaml
    dest: "{{ dir.ansible }}/headscale/config/config.yaml"
    mode: "0755"
    owner: 0
  tags: headscale
  notify:
    - restart headscale

- name: Move compose files
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ dir.ansible }}/headscale/docker-compose.yml"
    mode: "0700"
  tags: headscale
  notify:
    - restart headscale

- name: Start headscale
  community.docker.docker_compose_v2:
    project_src: "{{ dir.ansible }}/headscale"
    state: present
  tags: headscale

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers
  tags: headscale
