scrape_config_files:
  - /etc/vmagent/conf.d/*.yml
scrape_configs:
  - job_name: vmagent
    honor_labels: true
    basic_auth:
      username: 'vmagent-auth'
      password: {{ pwd }}
    static_configs:
      - targets: ["localhost:8429"]
        labels:
          instance: "{{ inventory_hostname }}"
  - job_name: "docker"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_io_path]
        regex: .+
        action: keep
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1
      - regex: __meta_docker_container_name
        action: labelmap
        replacement: container_name
      - source_labels: [ __meta_docker_container_label_prometheus_io_address ]
        regex: (.+)
        target_label: __address__
      - source_labels: [ __address__, __meta_docker_container_label_prometheus_io_port ]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
      - source_labels: [ __meta_docker_container_label_prometheus_io_path ]
        regex: (.+)
        target_label: __metrics_path__
      - source_labels: [ __meta_docker_container_label_prometheus_io_instance ]
        regex: (.+)
        target_label: instance
      - action: keepequal
        source_labels: [ __meta_docker_container_label_prometheus_io_network ]
        target_label: __meta_docker_network_name
      - action: labeldrop
        regex: (io_password|io_path|io_port|io_username|io_network)