services:
  vmagent:
    container_name: vmagent
    image: "{{ vmagent.image }}:{{ vmagent.version }}"
    restart: always
    volumes:
      - "{{ dir.ansible }}/vmagent/config:/etc/vmagent"
      - "{{ dir.data }}/vmagent:/vmagent"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
{% for key, value in vmagent.remoteWrite.items() %}
      - '-remoteWrite.{{ key }}={{ value }}'
{% endfor %}
      - '-httpListenAddr=127.0.0.1:8429'
      - '-httpAuth.username=vmagent-auth'
      - '-httpAuth.password=file:///etc/vmagent/password'
      - '-promscrape.config=/etc/vmagent/config.yml'
    user: 'root:root'
    network_mode: host