- tags: postgres
  when: postgres.role != 'standby'
  block:
  - name: Create prom-exporter user
    community.postgresql.postgresql_user:
      login_host: "{{ postgres_host | trim }}"
      login_password: "{{ postgres.password }}"
      login_user: "{{ postgres.username }}"
      name: "prom-exporter"
      password: "{{ mon_pwd }}"
    tags: postgres

  - name: Run several queries against acme db
    community.postgresql.postgresql_query:
      login_host: "{{ postgres_host | trim }}"
      login_password: "{{ postgres.password }}"
      login_user: "{{ postgres.username }}"
      query:
      - grant pg_monitor to prom-exporter

  - name: Rewrite compose file
    ansible.builtin.template:
      src: docker-compose.yml
      dest: "{{ dir.ansible }}/postgres-{{ postgres.name }}/docker-compose.yml"
      mode: 0700
    tags: postgres
  - name: Redeploy postgres container
    community.docker.docker_compose_v2:
      project_src: "{{ dir.ansible }}/postgres-{{ postgres.name }}"
    tags: postgres

- name: Clear monitoring password
  tags: postgres
  set_fact:
    mon_pwd: ''
