- tags: postgres
  when: postgres.role != 'standby'
  block:
  - name: Create prom-exporter user
    community.postgresql.postgresql_user:
      login_host: "{{ postgres_host | trim }}"
      login_password: "{{ postgres.password }}"
      login_user: "{{ postgres.username }}"
      name: "prom-exporter"
      password: "{{ mon_pwd }}"
    tags: postgres

  - name: Run several queries against acme db
    community.postgresql.postgresql_query:
      login_host: "{{ postgres_host | trim }}"
      login_password: "{{ postgres.password }}"
      login_user: "{{ postgres.username }}"
      query:
      - grant pg_monitor to prom-exporter

- name: Clear monitoring password
  tags: postgres
  set_fact:
    mon_pwd: ''
