---
- name: restart nginx
  community.docker.docker_compose_v2:
    project_src: "{{ dir.ansible }}/nginx-static-git-{{ nginx.static.git.name }}"
    restarted: true
    build: true
  tags: nginx_static_git
