version: '3.9'
networks:
  registry:
{% if 'alesharik.baseinfra.nginx_proxy' in ansible_role_names %}
  proxy:
    external:
      name: nginx-proxy_proxy
{% endif %}
services:
  registry:
    restart: always
    image: "registry:{{ docker.registry.server.version }}"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      VIRTUAL_HOST: "{{ docker.registry.server.host }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "{{ docker.registry.server.host }}"
    volumes:
      - "{{ docker.registry.server.directory }}:/var/lib/registry"
      - "{{ dir.ansible }}/docker-registry/htpasswd:/htpasswd"
    networks:
      - registry
{% if 'alesharik.baseinfra.nginx_proxy' in ansible_role_names %}
      - proxy
{% endif %}
